apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: terminus-issuer
  namespace: terminus
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: terminus-tls
  namespace: terminus
spec:
  secretName: terminus-tls
  dnsNames:
  - terminus-quota-service.terminus.svc
  - terminus-quota-service.terminus.svc.cluster.local
  issuerRef:
    name: terminus-issuer
    kind: ClusterIssuer